### ISSUE TITLE
Continuous deployment via Travis CI

### ISSUE THREAD

**Issue by teobais** [teobais/percircle#16]
Ok, we 're still on a beta version and when on production, **percircle** will still remain a small library, but providing automated builds will obviously boost the maintenance, as a whole.

Some links:
- http://awestruct.org/auto-deploy-to-github-pages/
- https://github.com/mfenner/jekyll-travis
- https://medium.com/@nthgergo/publishing-gh-pages-with-travis-ci-53a8270e87db

**Comment by toubou91** [comment]
Check also [surf](https://github.com/surf-build/surf).
