### ISSUE TITLE
Nothing Appears

### ISSUE THREAD

**Issue by mmeyer117** [teobais/percircle#63]
Hello,
I have downloaded the git repo and have been unable to get anything to work. Directly after downloading, I opened the index.html page, and none of the circles show up. Any clue as to why this is?

**Comment by thodorisbais** [comment]
Hey @mmeyer117 ,

thanks a lot for using `percircle`!

The behaviour is indeed a bit grumpy when you directly open the `index.html` file, as our index file is just a static file. On a side note, @chris--jones is there something we could improve here?

The project now supports webpack, so you could just perform hot deployment and live changes using the command `npm start`. Read more about how to build it locally [here](https://github.com/thodorisbais/percircle#building-percircle-locally)

Please let me know if that helped!

Thodoris

**Comment by chris--jones** [comment]
There's already a **Building Locally** section in the readme, but I suppose we could make it a bit more explicit?
Perhaps if we did a short table of contents with links to Using vs Developing?
Another idea would be to add helpful text to the index.html that is then replaced dynamically once the script is loaded successfully.

**Comment by thodorisbais** [comment]
As I mentioned above, I think the Building Locally section is quite self-explanatory at the moment, but I do think that this is a nice addition as well:

> Another idea would be to add helpful text to the index.html that is then replaced dynamically once the script is loaded successfully.

Could you please pick this up @chris--jones ?
