### ISSUE TITLE
Fill in the circle according to the server time

### ISSUE THREAD

**Issue by teobais** [teobais/percircle#70]
I recently received an email requesting this feature, so it would be nice if someone could have a look into it, otherwise I hope I can make some time during the Christmas period. Below the request:

_Is there a way to custom this to server time, lets say 0% is server time 8AM and 100% is 4PM? So if a visitor loads the page up at noon, your percentage circle would show automatically 50%_

**Comment by miller-kevin** [comment]
I wonder if this one's worth doing at all - ultimately this is just using the percentage. Nothing would stop the users from doing the simple math on an interval and setting a percircle percentage
