### ISSUE TITLE
Port to vue.js

### ISSUE THREAD

**Issue by teobais** [teobais/percircle#85]
According to https://stackoverflow.com/questions/69460136/percircle-dynamic-data-not-updating-in-vue-js and the latest trends, it would be nice to have a vuejs port of percircle

**Comment by miller-kevin** [comment]
I have been using this in my vue app (thank you for making this, by the way), and had intended to make a vue wrapper for it. I'll happily submit a PR when I finish. Do you want it to be in a different repo?

**Comment by teobais** [comment]
Thanks for using percircle, Kevin, that means a lot! Feel free to submit your PR as a different branch of the current repo, goal being the newly introduced branch (vuejs port) will become the master branch (subsequently positioning the current master as a secondary branch), thereby introducing the phasing out of the jQuery support in the long run (which will not be earlier than 2023 given the current usage).

Looking forward to reviewing your PR :)

**Comment by teobais** [comment]
Good catch, thanks. Updated old references, should be working now.

**Comment by teobais** [comment]
@miller-kevin shall I already assign this issue to you given the discussion above?

**Comment by miller-kevin** [comment]
Yes, I'll take it from here. Will let you know when the Vue rewrite is done

**Comment by teobais** [comment]
btw the intention of this issue is to fully migrate percircle to vuejs (no jQuery involved - percircle behavior developed in vuejs). If that is too costly for the time being, a wrapper is also fine and could be seen as a first step towards a future migration to vuejs.

**Comment by miller-kevin** [comment]
Yeah, I've already removed jQuery as a dependency. I planned for a wrapper, but what I'm doing is definitely a full conversion haha

**Comment by miller-kevin** [comment]
Feel free to review here https://github.com/teobais/percircle/pull/86

Needs some more testing (and maybe some back and forth with you about some of the changes made), but it definitely works.

I plan to implement it in my apps once I've had more time to test it

**Comment by teobais** [comment]
Closed with #86 . Thank you again, @miller-kevin 🎉
